### ISSUE TITLE
Không chạy được sau khi cài truffle

### ISSUE THREAD

**Issue by vanloc1808** [nhutminh9799/SolidityProgramming#12]
Em đã cài truffle bằng quyền admin với câu lệnh npm install -g truffle
Tuy nhiên, sau khi cài xong, gọi câu lệnh truffle unbox react thì nhân được lỗi như hình dưới, cho dù đã restart Terminal và mở lại.
![image](https://user-images.githubusercontent.com/76842571/177738141-3079e4ef-61aa-44a1-bc1c-97674f354a2d.png)
Em xin cảm ơn ạ.

**Comment by nhutminh9799** [comment]
Nhờ bạn thử lại bằng câu lệnh giúp nha
npm uninstall -g truffle
 npm install -g truffle

**Comment by vanloc1808** [comment]
Em cảm ơn anh ạ, em đã thử được rồi ạ
