### ISSUE TITLE
[RESEARCH] NGHIÊN CỨU STRING TRONG SOLIDITY CÓ BAO NHIÊU KÝ TỰ

### ISSUE THREAD

**Issue by nhutminh9799** [nhutminh9799/SolidityProgramming#2]

**Comment by VanLucNguyen** [comment]
-Một biến kiểu string có thể chứa một chuỗi có kích thước bất kì. Nhưng trong thực tế thì một biến string có giới hạn là 256*2^256.
-Về mặt kĩ thuật thì giới hạn của một biến string là 256*2^(256-1) do mã hóa độ dài.
-Thông thường chúng ta sẽ dùng biến kiển Byte32 để lưu các dữ liệu dạng chuỗi có độ dài dưới 32byte vì nó tốn ít chi phí gas hơn khi sử dụng.
