### ISSUE TITLE
[RESEARCH] NGHIÊN CỨU SWITCH CASE TRONG SOLIDITY

### ISSUE THREAD

**Issue by nhutminh9799** [nhutminh9799/SolidityProgramming#3]

**Comment by quandangminh2107** [comment]
Research/Issue/5_SwitchCase.sol

1. Assembly cho phép bạn thực thi một số logic có thể không thực hiện được chỉ với Solidity nhu switch case.
2. Switch nhận giá trị của một biểu thức và so sánh nó với một số hằng số ở phần Case. Nhánh tương ứng với hằng số phù hợp được chạy.
3. Tuy nhiên Switch cũng có một số hạn chế như:
- Phần swtich thì ko yêu cầu ngoặc nhọn nhưng phần Case lại có.
- Nếu đã bao phủ đc hết các khả năng thì ko đc dùng default.

Đã up file.

**Comment by nhutminh9799** [comment]
Research/Issue/5_SwitchCase.sol

Đã kiểm tra OK
