### ISSUE TITLE
[Lỗi Deploy] Error: The data field must be HEX encoded data.

### ISSUE THREAD

**Issue by nhutminh9799** [nhutminh9799/SolidityProgramming#5]
pragma solidity ^0.8.6;

library Search {
   function indexOf(uint[] storage self, uint value) public view returns (uint) {
      for (uint i = 0; i < self.length; i++)
      {
        if (self[i] == value)
        return i;
      }
      
        return uint(int(-1));
   }
}

/**
 * Using Test Library
 */
contract Test {
   using Search for uint[];
   uint[] public data;

    constructor() public{
        data.push(1);
        data.push(2);
        data.push(3);
        data.push(4);
        data.push(5);
    }

   function isValuePresent() public view returns(uint){
      uint value = 4;      
      
      //Now data is representing the Library
      uint index = data.indexOf(value);
      return index;
   }
}

Khi chạy đoạn code trên môi trường VS Code --> Contract Test gây ra lỗi Error: The data field must be HEX encoded data.

**Comment by quandangminh2107** [comment]
### **Cách fix lỗi trên**
1. Tại hàm indexOf() của library Search:

> function indexOf(uint[] storage self, uint value) public view returns (uint) {
      for (uint i = 0; i < self.length; i++)
      {
        if (self[i] == value)
        return i;
      }
        return uint(int(-1));
   }

Ta sửa public -> internal thành như sau:

> function indexOf(uint[] storage self, uint value) internal view returns (uint) {
        for (uint i = 0; i < self.length; i++)
        {
            if (self[i] == value)
            return i;
        }
        return uint(int(-1));
   }

2. Tại hàm isValuePresent() của contract Test:

> function isValuePresent() public view returns(uint){
      uint value = 4;      
      //Now data is representing the Library
      uint index = data.indexOf(value);
      return index;
   }

Ta sửa public -> external thành như sau:

> function isValuePresent() external view returns(uint){
      uint value = 4;      
      //Now data is representing the Library
      uint index = data.indexOf(value);
      return index;
   }

**Comment by nhutminh9799** [comment]
Đã OK
