### ISSUE TITLE
[Lỗi cài đặt] Cài Extention Ethereum Remix gặp lỗi

### ISSUE THREAD

**Issue by phamquangviet** [nhutminh9799/SolidityProgramming#8]
Chào mọi người, 

Mình cài Ethereum Remix trên vscode nhưng bảng Remix không hiện các tool như được hướng dẫn. 

Bạn nào fix được giúp mình với, mình cảm ơn

![image](https://user-images.githubusercontent.com/86511743/177554633-5e413b07-46ff-47fd-bd9a-fc383ded01bd.png)

**Comment by VanLucNguyen** [comment]
Bạn phải Open nguyên folder luôn nó mới có ạ. Còn bạn Open file thì nó không hiện tool đâu ạ.

**Comment by phamquangviet** [comment]
Oh mình vừa mở nguyên 1 folder thì nó hiện ra các tool rồi, 
Mình cảm ơn bạn nhiều nha!
