### ISSUE TITLE
Nhờ giúp đỡ

### ISSUE THREAD

**Issue by phuocmien** [nhutminh9799/SolidityProgramming#9]
Mình cài Ganache bị lỗi, nhờ nhóm hỗ trợ.
This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)

cảm ơn các bạn

**Comment by nhutminh9799** [comment]
Cảm ơn anh đã đưa ra câu hỏi về Ganache chỗ này. 
![image](https://user-images.githubusercontent.com/48749320/177618441-99f2f3b4-b23f-4d2b-864a-102740848a75.png)
Tại trang này anh xin vào chỗ [Need another OS download?](https://github.com/trufflesuite/ganache-ui/releases)
Sau đó xuống phía dưới 
![image](https://user-images.githubusercontent.com/48749320/177618586-687313ed-3409-48be-93e6-69cc32b34d5c.png)
Chọn bản [Ganache-2.5.4-win-setup.exe](https://github.com/trufflesuite/ganache-ui/releases/download/v2.5.4/Ganache-2.5.4-win-setup.exe)
Nhờ anh cài lại giúp em chỗ này.

**Comment by phuocmien** [comment]
Cảm ơn em đã hỗ trợ;
Anh đã install được theo cách của em.
Thanks.
